### ISSUE TITLE
想请问是用什么写的电路并生成的验证合约？

### ISSUE THREAD

**Issue by Vap0RSh4wN** [imamtom/BZDIMS#2]

**Comment by Vap0RSh4wN** [comment]
没事了(*/ω＼*)，我才看到readme，感谢！

**Comment by imamtom** [comment]
ZoKrates... 但现在有更多的选择, 包括circom, halo2

**Comment by Vap0RSh4wN** [comment]
> ZoKrates... 但现在有更多的选择, 包括circom, halo2

好滴，感谢！！
